name: Unpack SquashFS

on:
  push:
    branches: [ unpack ]

jobs:
  unpack:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install squashfs-tools
      run: sudo apt-get update && sudo apt-get install -y squashfs-tools

    - name: Run unpack.sh to extract mtd4
      run: |
        chmod +x unpack.sh
        ./unpack.sh

    - name: Compress squashfs-root to zip
      run: |
        zip -r squashfs-root.zip squashfs-root

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: squashfs-root
        path: squashfs-root.zip
